name: projrect_annam
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.0.2 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  flutter_rating_bar: ^4.0.1

  image_picker: ^1.1.2
  http: ^1.1.0
  flutter_easyloading: ^3.0.5
  shared_preferences: ^2.2.3

  google_maps_flutter: ^2.3.1
  custom_map_markers: ^0.0.2+1

  intl: ^0.19.0
  flutter_timezone: ^1.0.6
  carousel_slider: ^4.2.1
  calendar_date_picker2: ^1.1.5
  font_awesome_flutter: ^10.7.0
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  firebase_storage: ^12.1.1
  cloud_firestore: ^5.1.0
  provider: ^6.1.2
  shimmer: ^3.0.0
  rive: ^0.13.12
  flutter_animate: ^4.5.0
  flutter_riverpod: ^2.5.1
  lottie: ^3.1.2
  google_nav_bar: ^5.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/rive/
    - assets/images/
    - assets/lottie/
  fonts:
    - family: Metropolis
      fonts:
        - asset: assets/font/Metropolis-Regular.otf
        - asset: assets/font/Metropolis-Medium.otf
          weight: 500
        - asset: assets/font/Metropolis-SemiBold.otf
          weight: 600
        - asset: assets/font/Metropolis-Bold.otf
          weight: 700
        - asset: assets/font/Metropolis-ExtraBold.otf
          weight: 800